# GNSS Configuration for ZED Integration
# =====================================

gnss_driver:
  # Hardware configuration
  device: /dev/ttyACM0              # GNSS receiver serial port
  baudrate: 115200                  # Serial communication rate
  frame_id: gnss_link               # TF frame for GNSS antenna
  
  # Update rates
  measurement_rate: 10              # GNSS measurement rate (Hz)
  navigation_rate: 5                # Navigation solution rate (Hz)
  
  # Fix configuration
  fix_mode: auto                    # auto, 2d, 3d
  dynamic_model: automotive         # portable, automotive, airborne
  
  # Quality settings
  min_fix_type: 3                   # Minimum fix type (1=no_fix, 2=2d, 3=3d)
  min_satellites: 4                 # Minimum satellites for valid fix
  max_hdop: 5.0                    # Maximum horizontal dilution of precision
  max_vdop: 10.0                   # Maximum vertical dilution of precision
  
  # ZED integration settings
  publish_rate: 10.0               # ROS topic publish rate (Hz)
  enable_rtk: false                # Enable RTK corrections (if available)
  rtk_correction_topic: /rtk/corrections
  
  # Data publishing
  publish:
    fix: true                      # Publish NavSatFix messages
    vel: true                      # Publish velocity
    time: false                    # Don't publish time (use system time)
    imu: false                     # Don't publish IMU (ZED provides IMU)
    utc: false                     # Don't publish UTC time
    
# GNSS diagnostics configuration
gnss_diagnostics:
  # Health monitoring
  enable_health_monitoring: true
  health_check_rate: 1.0           # Health check frequency (Hz)
  
  # Quality thresholds
  signal_strength_threshold: -130   # Minimum signal strength (dBm)
  satellite_count_threshold: 4     # Minimum satellite count
  hdop_threshold: 2.0              # HDOP quality threshold
  fix_timeout: 10.0                # Fix timeout (seconds)
  
  # Alert settings
  enable_quality_alerts: true      # Enable quality degradation alerts
  alert_hysteresis: 2.0           # Prevent alert flapping (seconds)
