<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- =============================================================================
       PARAMETERIZED GRIPPER TEMPLATE
       =============================================================================
       Generic parallel gripper that can be attached to any arm.
       All parameters are configurable through arm_params.yaml
       ============================================================================= -->

  <xacro:macro name="gripper_template" params="parent name max_opening finger_length finger_width palm_size">
    
    <!-- Material definitions -->
    <material name="gripper_black">
      <color rgba="0.1 0.1 0.1 1.0"/>
    </material>
    
    <material name="gripper_grey">
      <color rgba="0.6 0.6 0.6 1.0"/>
    </material>

    <!-- =============================================================================
         GRIPPER PALM (Base)
         ============================================================================= -->
    <link name="${name}_palm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${palm_size[0]} ${palm_size[1]} ${palm_size[2]}"/>
        </geometry>
        <material name="gripper_black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${palm_size[0]} ${palm_size[1]} ${palm_size[2]}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <!-- Joint connecting gripper to arm -->
    <joint name="${name}_mount" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_palm"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </joint>

    <!-- =============================================================================
         LEFT FINGER
         ============================================================================= -->
    <link name="${name}_left_finger">
      <visual>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${finger_width} ${finger_width} ${finger_length}"/>
        </geometry>
        <material name="gripper_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${finger_width} ${finger_width} ${finger_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>

    <!-- Left finger joint (prismatic) -->
    <joint name="${name}_left_finger_joint" type="prismatic">
      <parent link="${name}_palm"/>
      <child link="${name}_left_finger"/>
      <origin xyz="0 ${max_opening/2} ${palm_size[2]/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="0.0" upper="${max_opening/2}" velocity="0.1" effort="100.0"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- =============================================================================
         RIGHT FINGER
         ============================================================================= -->
    <link name="${name}_right_finger">
      <visual>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${finger_width} ${finger_width} ${finger_length}"/>
        </geometry>
        <material name="gripper_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${finger_width} ${finger_width} ${finger_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>

    <!-- Right finger joint (prismatic, mirrored) -->
    <joint name="${name}_right_finger_joint" type="prismatic">
      <parent link="${name}_palm"/>
      <child link="${name}_right_finger"/>
      <origin xyz="0 ${-max_opening/2} ${palm_size[2]/2}" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit lower="0.0" upper="${max_opening/2}" velocity="0.1" effort="100.0"/>
      <dynamics damping="0.1" friction="0.1"/>
      <mimic joint="${name}_left_finger_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <!-- =============================================================================
         FINGERTIPS (Contact surfaces)
         ============================================================================= -->
    <link name="${name}_left_fingertip">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${finger_width/4}"/>
        </geometry>
        <material name="gripper_black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${finger_width/4}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
                 iyy="0.00001" iyz="0.0" izz="0.00001"/>
      </inertial>
    </link>

    <joint name="${name}_left_fingertip_joint" type="fixed">
      <parent link="${name}_left_finger"/>
      <child link="${name}_left_fingertip"/>
      <origin xyz="0 0 ${finger_length}" rpy="0 0 0"/>
    </joint>

    <link name="${name}_right_fingertip">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${finger_width/4}"/>
        </geometry>
        <material name="gripper_black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${finger_width/4}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
                 iyy="0.00001" iyz="0.0" izz="0.00001"/>
      </inertial>
    </link>

    <joint name="${name}_right_fingertip_joint" type="fixed">
      <parent link="${name}_right_finger"/>
      <child link="${name}_right_fingertip"/>
      <origin xyz="0 0 ${finger_length}" rpy="0 0 0"/>
    </joint>

    <!-- =============================================================================
         GAZEBO GRIPPER PLUGIN
         ============================================================================= -->
    <gazebo>
      <plugin name="${name}_grasp_plugin" filename="libgazebo_ros_gripper.so">
        <robot_namespace>/</robot_namespace>
        <arm_name>${name}</arm_name>
        <grasp_check>
          <attach_steps>20</attach_steps>
          <detach_steps>40</detach_steps>
          <min_contact_count>2</min_contact_count>
        </grasp_check>
        <gripper_link>${name}_palm</gripper_link>
        <palm_link>${name}_palm</palm_link>
        <finger_links>
          <link>${name}_left_fingertip</link>
          <link>${name}_right_fingertip</link>
        </finger_links>
      </plugin>
    </gazebo>

    <!-- Gazebo materials -->
    <gazebo reference="${name}_palm">
      <material>Gazebo/Black</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
    </gazebo>
    
    <gazebo reference="${name}_left_finger">
      <material>Gazebo/Grey</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
    </gazebo>
    
    <gazebo reference="${name}_right_finger">
      <material>Gazebo/Grey</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
    </gazebo>
    
    <gazebo reference="${name}_left_fingertip">
      <material>Gazebo/Black</material>
      <mu1>2.0</mu1>
      <mu2>2.0</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>
    
    <gazebo reference="${name}_right_fingertip">
      <material>Gazebo/Black</material>
      <mu1>2.0</mu1>
      <mu2>2.0</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>

  </xacro:macro>

</robot> 