# path to exported ONNX model
model_path:     $(find object_detection)/models/sample_model.onnx

# list of classes (must match your network’s training order)
classes_file:   $(find object_detection)/models/classes.txt

# minimum confidence to accept a detection
confidence_threshold: 0.5

# topic names
image_topic:    /zed2i/left/image_rect_color
output_topic:   /detected_objects
