# Spatial Mapping Configuration
# =============================

spatial_mapping:
  # Core mapping parameters
  mapping_enabled: true                     # Enable GPU spatial mapping
  resolution: 0.05                          # Map resolution (meters per voxel)
  max_mapping_range: 10.0                   # Maximum mapping range (meters)
  fused_pointcloud_freq: 2.0               # Fused cloud publish rate (Hz)
  
  # Topic configuration
  fused_cloud_topic: '/camera/mapping/fused_cloud'
  occupancy_grid_topic: '/map'
  plane_topic: '/camera/mapping/plane'
  
  # Quality control
  min_points_per_voxel: 3                   # Minimum points for voxel validity
  max_memory_usage_mb: 1024                 # Maximum GPU memory usage
  enable_mesh_generation: false             # Generate textured meshes
  
  # Performance optimization
  enable_performance_monitoring: true       # Monitor mapping performance
  performance_log_interval: 5.0            # Performance logging interval (seconds)
  auto_optimize_parameters: true           # Auto-tune for performance
  
  # Integration settings
  publish_occupancy_grid: true              # Convert to occupancy grid for Nav2
  grid_resolution: 0.05                     # Occupancy grid resolution
  grid_size_x: 2048                        # Grid width (cells)
  grid_size_y: 2048                        # Grid height (cells)
  
  # Plane detection
  enable_plane_detection: true              # Detect ground/wall planes
  plane_detection_threshold: 0.15          # Plane detection sensitivity
  min_plane_size: 1.0                      # Minimum plane area (m²)

# Camera spatial mapping parameters (passed to camera wrapper)
camera_spatial_mapping:
  # Core mapping settings
  mapping_enabled: true
  resolution: 0.05                          # Mapping resolution (meters)
  max_mapping_range: 10.0                   # Maximum range (meters)
  
  # Performance settings
  use_chunk_only: true                      # Memory optimization
  max_memory_usage: 2048                    # Maximum memory (MB)
  
  # Update control
  fused_pointcloud_freq: 2.0               # Update frequency (Hz)
  clicked_point_topic: '/clicked_point'     # RViz interaction
  
  # Plane detection parameters
  pd_max_distance_threshold: 0.15          # Plane detection threshold
  pd_normal_similarity_threshold: 15.0     # Plane normal similarity (degrees)
  
  # Quality settings
  enable_texture_mapping: true              # Enable colored mapping
  texture_confidence_threshold: 100        # Texture confidence threshold
