# URC Perception Data Recording Configuration
# ==========================================

perception_recorder:
  # Recording settings
  output_directory: "/home/rover/perception_data"
  bag_prefix: "urc_perception"
  max_bag_size_mb: 2048
  max_bag_duration_sec: 600  # 10 minutes per bag
  compression: "zstd"
  
  # Topics to record
  core_topics:
    # Camera data
    - "/zed2i/left/image_rect_color"
    - "/zed2i/right/image_rect_color" 
    - "/zed2i/depth/depth_registered"
    - "/zed2i/point_cloud/cloud_registered"
    
    # Sensor data
    - "/zed2i/imu/data"
    - "/zed2i/odom"
    - "/gnss/fix"
    
    # Localization
    - "/odometry/filtered"
    - "/odometry/global"
    
    # Mapping
    - "/map"
    - "/local_map"
    - "/scan"
    - "/rtabmap/cloud_map"
    
    # Transforms
    - "/tf"
    - "/tf_static"

  detection_topics:
    # Object detection
    - "/detected_objects"
    - "/aruco_detections" 
    - "/target_pose"
    
  # Recording modes
  modes:
    full:
      description: "Record all perception data"
      topics: ["core_topics", "detection_topics"]
      
    slam_only:
      description: "Record only SLAM-related data"
      topics: ["core_topics"]
      
    detection_only:
      description: "Record only detection data"
      topics: ["detection_topics", "/zed2i/left/image_rect_color"]
      
    minimal:
      description: "Record essential data only"
      topics: [
        "/zed2i/left/image_rect_color",
        "/zed2i/imu/data", 
        "/gnss/fix",
        "/odometry/filtered",
        "/map"
      ]

  # Auto-management
  auto_cleanup: true
  keep_last_n_bags: 10
  cleanup_older_than_days: 7
