controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]

  FollowPath:
    plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
    desired_linear_vel: 0.55
    max_linear_accel: 2.5
    max_linear_decel: 2.5
    desired_angular_vel: 1.0
    max_angular_accel: 3.2
    lookahead_dist: 1.5
    min_lookahead_dist: 0.3
    max_lookahead_dist: 2.5
    lookahead_time: 1.5
    curvature_vel_exponent: 1.0
    curvature_vel_factor: 1.3
    costmap_threshold: 100
    inflation_radius: 0.4
    regulated_linear_scaling: 0.25
    proximity_threshold: 0.6
    goal_dist_tol: 0.15
    goal_angle_tol: 0.15
    transform_tolerance: 0.1

#    FollowPath:
#      plugin: "nav2_dwb_controller/DWBLocalPlanner"
#      # Simulation parameters
#      sim_time: 1.5
#      sim_granularity: 0.2
#      # Velocity limits
#      max_vel_x: 0.5
#      min_vel_x: 0.0
#      max_vel_theta: 1.0
#      min_vel_theta: -1.0
#      acc_lim_x: 2.5
#      acc_lim_theta: 3.2
#      # Scoring parameters
#      path_distance_bias: 32.0
#      goal_distance_bias: 24.0
#      occdist_scale: 0.01
#      forward_point_distance: 0.325
#      heading_lookahead: 0.325
#      pdist_scale: 0.6
#      gdist_scale: 0.8
#      oscillation_timeout: 0.0
#      oscillation_distance: 0.0
