amcl:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    ros__parameters:
      use_sim_time: false
      yaml_filename: ''

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ['map_server',
                 'planner_server',
                 'controller_server',
                 'behavior_server',
                 'bt_navigator']

# Include costmap and planner/controller configurations
