costmap_local:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    transform_tolerance: 0.5
    
    static_map: false
    rolling_window: true
    width: 8.0
    height: 8.0
    resolution: 0.05
    
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: "scan"
      scan:
        topic: "/scan"
        data_type: "LaserScan"
        expected_update_rate: 10.0
        min_obstacle_height: 0.0
        max_obstacle_height: 2.0
        obstacle_range: 10.0
        raytrace_range: 12.0
        clearing: true
        marking: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
