# Global Localization Configuration
# =================================

global_localization:
  # Topic configuration
  gnss_topic: '/gps/fix'                    # GNSS input topic
  fused_pose_topic: '/camera/gnss/pose'     # Camera-GNSS fused pose
  geo_pose_topic: '/camera/geo_pose'        # Geographic pose output
  local_pose_topic: '/odometry/filtered'    # Local VIO fallback
  
  # Quality thresholds
  gnss_timeout: 10.0                        # GNSS timeout (seconds)
  fusion_quality_threshold: 0.8             # Minimum fusion quality (0-1)
  position_accuracy_threshold: 2.0          # Maximum position error (meters)
  
  # Behavior settings
  enable_auto_fallback: true                # Auto-switch to local when GNSS poor
  enable_origin_auto_set: true              # Auto-set origin from first GPS fix
  enable_waypoint_navigation: true          # Enable GPS waypoint navigation
  
  # Coordinate system settings
  default_utm_zone: ''                      # UTM zone (auto-detect if empty)
  map_origin_lat: 0.0                       # Fixed origin latitude (0.0 = auto)
  map_origin_lon: 0.0                       # Fixed origin longitude (0.0 = auto)
  map_origin_alt: 0.0                       # Fixed origin altitude (0.0 = auto)
  
  # Performance settings
  monitoring_rate: 1.0                      # Health monitoring rate (Hz)
  coordinate_conversion_cache_size: 100     # Cache recent conversions
  
# Camera GNSS fusion parameters (passed to camera wrapper)
camera_gnss_fusion:
  # Enable fusion in camera
  fusion_enabled: true
  
  # GNSS input
  gnss_fix_topic: '/gps/fix'
  gnss_zero_altitude: false                 # Ignore altitude (use for 2D missions)
  
  # Fusion quality control
  enable_reinitialization: true             # Re-init when GNSS/VIO diverge
  enable_rolling_calibration: true          # Continuous calibration refinement
  gnss_vio_reinit_threshold: 5.0           # Reinit threshold (meters)
  
  # Uncertainty targets
  enable_translation_uncertainty_target: true
  target_translation_uncertainty: 0.1       # Target position accuracy (meters)
  target_yaw_uncertainty: 0.1               # Target heading accuracy (radians)
  
  # Covariance scaling
  h_covariance_mul: 1.0                     # Horizontal covariance multiplier
  v_covariance_mul: 1.0                     # Vertical covariance multiplier
  
  # Transform publishing
  publish_utm_tf: true                      # Publish UTM transform
  broadcast_utm_transform_as_parent_frame: false
