# =============================================================================
# KINEMATICS SOLVER CONFIGURATION FOR ROVER ARM
# =============================================================================
# This configuration specifies the kinematics solver for inverse kinematics
# calculations. The rover arm has 4 DOF, so we use KDL for fast IK solving.
# =============================================================================

arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3

